name: chat
description: Chat App by MTM
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.7
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  freezed: ^2.4.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.1
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.1
  twitter_login: ^4.4.2
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/assets/

flutter_native_splash:
  color: "#2E2E2E"
  image: "assets/images/splash.png"
  fullscreen: true
  android_12:
    color: "#2E2E2E"
    image: "assets/images/splash.png"

