// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq0HC_PycR-j5hx7yBVqeuv6nR0T9umHE',
    appId: '1:106736854339:web:0653f9f8d22bd4625afbf6',
    messagingSenderId: '106736854339',
    projectId: 'flutterojt',
    authDomain: 'flutterojt.firebaseapp.com',
    storageBucket: 'flutterojt.appspot.com',
    measurementId: 'G-E0N8WX3X86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5VtYUgfGO_b1oUP1fC2IZev1PmgDRd-I',
    appId: '1:106736854339:android:5d3c993be6b4976a5afbf6',
    messagingSenderId: '106736854339',
    projectId: 'flutterojt',
    storageBucket: 'flutterojt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZtljB_HFh0GXA3XBksOvp3zGsTwIqv0',
    appId: '1:106736854339:ios:2ac4c3fc60c605c75afbf6',
    messagingSenderId: '106736854339',
    projectId: 'flutterojt',
    storageBucket: 'flutterojt.appspot.com',
    iosClientId: '106736854339-5pa0e21br344rdmbt1c9dfpgohb9llm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterojt',
  );
}
